# Generated by Django 2.2.2 on 2021-03-04 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chain',
            fields=[
                ('ChainId', models.IntegerField(primary_key=True, serialize=False)),
                ('Node1Id', models.IntegerField(default='')),
                ('Node2Id', models.IntegerField(default='')),
                ('EdgeId', models.IntegerField(default='')),
                ('Node1IdName', models.CharField(default='', max_length=100)),
                ('Node2IdName', models.CharField(default='', max_length=100)),
                ('EdgeName', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='edge',
            fields=[
                ('EdgeId', models.IntegerField(primary_key=True, serialize=False)),
                ('EdgeName', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='node',
            fields=[
                ('NodeId', models.IntegerField(primary_key=True, serialize=False)),
                ('NodeName', models.CharField(default='', max_length=100)),
                ('PreEdgeId', models.IntegerField(default='')),
                ('NextEdgeId', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='paper',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='relationship',
            fields=[
                ('PoemId', models.IntegerField(default='')),
                ('PoemSenId', models.IntegerField(primary_key=True, serialize=False)),
                ('PoemName', models.CharField(default='', max_length=100)),
                ('PoemSenName', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='t_node',
            fields=[
                ('StNodeId', models.IntegerField(default='')),
                ('EdNodeId', models.IntegerField(default='')),
                ('StNodeName', models.CharField(default='', max_length=100)),
                ('EdNodeName', models.CharField(default='', max_length=100)),
                ('PoemName', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='selection',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Question', models.CharField(default='', max_length=150)),
                ('A', models.CharField(default='', max_length=100)),
                ('B', models.CharField(default='', max_length=100)),
                ('C', models.CharField(default='', max_length=100)),
                ('D', models.CharField(default='', max_length=100)),
                ('Answer', models.CharField(default='', max_length=2)),
                ('Title2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tp.paper')),
            ],
        ),
    ]
