# Generated by Django 3.2.16 on 2024-03-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('author', models.CharField(max_length=255)),
                ('dynasty', models.CharField(max_length=10)),
                ('previous_content', models.CharField(max_length=255)),
                ('extracted_content', models.CharField(max_length=255)),
                ('latter_content', models.CharField(max_length=255)),
                ('keyword', models.CharField(max_length=10)),
            ],
        ),
    ]
