# Generated by Django 2.2.2 on 2021-03-10 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('niji', '0002_auto_20210216_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='favourite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('node_no', models.CharField(default='', max_length=255)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favour', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
